# -*- coding: utf-8 -*-
"""DAY 1 : Introduction and Setup.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kRlK-jW-QSAphrpIcuz7WcDsjC8t4Vyl
"""

# Q1: Write a Python program to print "Hello, World!"

print("Hello, World!")

# Q2: Calculate the sum of two numbers entered by the user.

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
sum = num1 + num2
print("Sum:", sum)

# Q3: Convert temperature from Celsius to Fahrenheit.

celsius = float(input("Enter temperature in Celsius: "))
fahrenheit = (celsius * 9/5) + 32
print("Temperature in Fahrenheit:", fahrenheit)

# Q4: Given a list of numbers, find the maximum and minimum values.

numbers = [3, 7, 2, 9, 5]
max_value = max(numbers)
min_value = min(numbers)
print("Maximum:", max_value)
print("Minimum:", min_value)

# Q5: Create a Python function to check if a given string is a palindrome.

def is_palindrome(s):
    return s == s[::-1]

# Example usage
string = "radar"
if is_palindrome(string):
    print("Palindrome")
else:
    print("Not a palindrome")

# Q6: Calculate the compound interest for a given principal amount, interest rate, and time period.

principal = float(input("Enter the principal amount: "))
rate = float(input("Enter the interest rate (in percentage): "))
time = float(input("Enter the time period (in years): "))
rate = rate / 100
compound_interest = principal * (1 + rate) ** time - principal
print("Compound Interest:", compound_interest)

# Q7: Write a Python program to calculate the area of a rectangle given its length and width.

length = float(input("Enter the length of the rectangle: "))
width = float(input("Enter the width of the rectangle: "))
area = length * width
print("The area of the rectangle is:", area)

# Q8: Create a program that takes a user's name and age as input and prints a greeting message.

name = input("Enter your name: ")
age = int(input("Enter your age: "))
print("Hello,", name + "! You are", age, "years old.")

# Q9: Write a program to check if a number is even or odd.

number = int(input("Enter a number: "))
if number % 2 == 0:
    print(number, "is even.")
else:
    print(number, "is odd.")

# Q10: Write a program that converts a given number of days into years, weeks, and days.

total_days = int(input("Enter the number of days: "))
years = total_days // 365
weeks = (total_days % 365) // 7
days = (total_days % 365) % 7
print("Years:", years)
print("Weeks:", weeks)
print("Days:", days)

# Q11: Given a list of integers, find the sum of all positive numbers.
numbers = [-1, 2, -3, 4, -5, 6]
positive_sum = 0
for num in numbers:
    if num > 0:
        positive_sum += num
print("Sum of positive numbers:", positive_sum)

# Q12: Create a program that takes a sentence as input and counts the number of words in it.

sentence = input("Enter a sentence: ")
word_count = len(sentence.split())
print("Number of words:", word_count)

# Q13: Implement a program that swaps the values of two variables.

a = 5
b = 10
print("Before swapping:")
print("a =", a)
print("b =", b)

a, b = b, a
print("After swapping:")
print("a =", a)
print("b =", b)